# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50a8ce56ec64a8e8e75a4fe01044a391439a0289224b267c98f9048588bbb0e4d97a5b326ffe8a0da67ba515768909e27d0c5ef83482fbfa6b685ba0683c9cac

test:
  secret_key_base: 8c06f709bc9a58faf7ac3bec9619c1295853bbc7db6935a4beb95b7bef2678018d05a2983a8ba91b9677e843ebdfe2126dfddc7f0e368b1f6e6b8328efc55d80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
